name: Run AI Scraper Daily

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 19:00 UTC
  workflow_dispatch:  # Allow manual execution

jobs:
  run-scraper:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'  # Specify the Python version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-scraper/requirements.txt  # Assuming you have a requirements.txt file

      # Run the Python script with secrets
      - name: Run AI Scraper
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SERAPI_KEY: ${{ secrets.SERAPI_KEY }}
        run: |
          python ai-scraper/index.py
